# Generated by Django 5.0.3 on 2024-03-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
